// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Marinheiro de frente":return img`
.........99...2.....
........9999.2......
.......222222.......
......99999999......
......dddddddd......
......ddfddfdd......
......dddddddd......
......ddf22fdd......
.........dd.........
....897a3aaaa252....
....869a3fffa424....
....669f3af3a252....
....969afaf3f424....
....989a3fffa252....
.....d.a3a3aa.d.....
.......a3aa3a.......
........8888........
........8888........
........dddd........
........ffff........
`;
            case "image2":
            case "Marinheiro virado para a direita":return img`
........99..........
.......9999.........
......222222........
.....99999999.......
......dddd1e........
......dddd11........
......dddddd........
........dd..........
.......2542.........
.......5245.........
.......5545.........
.......2524.........
.......4522.........
.......5dd5.........
.......5dd5.........
.......2452.........
........88..........
........88..........
........dd..........
........ff..........
`;
            case "image3":
            case "Marinheiro virado para a esquerda":return img`
........99..........
.......9999.........
......222222........
.....99999999.......
......e1dddd........
......11dddd........
......dddddd........
........dd..........
.......9887.........
.......9978.........
.......9969.........
.......9996.........
.......9769.........
.......9dd9.........
.......9dd9.........
.......9999.........
........88..........
........88..........
........dd..........
........ff..........
`;
            case "image4":
            case "Ulisses de frente":return img`
....................
....................
..........ee........
.....eeeeeeeee......
.....eeeeeddee......
....eeddddddee......
....ee11dd11eee.....
.....e1edde1eee.....
......ddddddee......
......99dd99........
..dd9999999999dd....
..dd9999999999dd....
.ddd9999999999ddd...
.ddd9999999999ddd...
..dd9999999999dd....
..ddeeeeeeeeeedd....
....9999999999......
....9999999999......
....dd......dd......
....dd......dd......
`;
            case "image5":
            case "Ulisses virado para a esquerda":return img`
....................
....................
..........ee........
.......eeeeeee......
........eeeeee......
........eeeeee......
........11deeee.....
........e1ddeee.....
........ddddee......
........9ddd........
........9dd9........
........9dd9........
........9ddd........
........9ddd........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
            case "image6":
            case "Ulisses virado para a direita":return img`
....................
....................
........ee..........
......eeeeeee.......
......eeeeee........
......eeeeee........
....eeeeed11........
....eeeedd1e........
......eedddd........
........ddd9........
........9dd9........
........9dd9........
........ddd9........
........ddd9........
........9dd9........
........edde........
........9999........
........9999........
........dddd........
........dddd........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
